services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_PATH: /dev-toolbox
    ports:
      - '80:80'
    networks:
      - basenet

networks:
  basenet:
